# Generated by Django 6.0.3 on 2026-06-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User')], max_length=15),
        ),
    ]
